QUESTIONS_PER_PAGE = 5
ATTEMPT_SELECTION_MODE_STANDARD = "standard"
ATTEMPT_SELECTION_MODE_ERROR_FOCUS = "error_focus"
ERROR_FOCUS_DEFAULT_FAILURE_PERCENTAGE_THRESHOLD = 40
ERROR_FOCUS_MINIMUM_FAILURE_COUNT = 2
ERROR_FOCUS_PREVIEW_LIMIT = 5
